### ISSUE TITLE
--------

### ISSUE THREAD

**Issue by achefinil** [NervJS/taro#2236]
**问题描述**
---------

**Comment by luckyadam** [comment]
SEO 问题请网上搜索一下

**Comment by invinjun** [comment]
这问题为什么在这里问?无奈....

**Comment by richerdcrainum1** [comment]
Nobody is been given permission  for this on this device... The male spouse
 is coding w o permission... Looking  for legal action  and WILL BE
OBTAINING  SECURE DEVICE... SEE U SOOM

On Mar 27, 2019 1:33 AM, "Kim Seong" <notifications@github.com> wrote:

Closed #2236 <https://github.com/NervJS/taro/issues/2236>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NervJS/taro/issues/2236#event-2232275850>, or mute the
thread
