### ISSUE TITLE
RN端编译时提示Warning: isMounted(...) is deprecated in plain JavaScript React classes.

### ISSUE THREAD

**Issue by fuchenxu2008** [NervJS/taro#642]
**问题描述**
Taro编译RN时会有持续的Warnings提示，如图。

**复现步骤**
运行`npm run dev:rn`以及每次更新重新编译时均会出现。

**期望行为**
不提示以上Warning

**报错信息**
![](https://ws4.sinaimg.cn/large/006tNbRwgy1fvdpvdtbunj317u0af77t.jpg)

**系统信息**

 - 操作系统: MacOS Mojave 10.14
 - Taro 版本 1.0.0 beta30
 - Node.js 版本 v9.4.0

**Comment by Phitchy** [comment]
This is my account mxiulian@gmail.com Ma Xiu Lian
I didn't get enough of you guys
What matters?

On Sep 18, 2018 2:22 PM, "Steve" <notifications@github.com> wrote:

*问题描述*
Taro编译RN时会有持续的Warnings提示，如图。

*复现步骤*
运行npm run dev:rn以及每次更新重新编译时均会出现。

*期望行为*
不提示以上Warning

*报错信息*
<https://camo.githubusercontent.com/f25d2821ddb036efac140e924b709c348299e9a2/68747470733a2f2f7773342e73696e61696d672e636e2f6c617267652f303036744e6252776779316676647076647462756e6a333137753061663737742e6a7067>

*系统信息*

   - 操作系统: MacOS Mojave 10.14
   - Taro 版本 1.0.0 beta30
   - Node.js 版本 v9.4.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NervJS/taro/issues/642>, or mute the thread

**Comment by Pines-Cheng** [comment]
打开调试窗口（使用 Chorome 或 react-native-debugger）这些警告信息就不会在终端显示了，至于为什么显示这些警告，还得排查一下。

**Comment by Pines-Cheng** [comment]
Since updating to new version of React Native 0.55 we all have been starting to seeing a yellow error message box in our newly build react native application “Warning: isMounted(…) is deprecated in plain JavaScript React Classes. Instead, make sure to clean up subscriptions and pending request in componentWillUnmount to prevent memory leaks.” This error message is coming because of some comparability issue of react native current version. There is no need to worry this is simply a error message and can be easily hide. So in this tutorial we would going to Solve Warning isMounted(…) is deprecated in plain JavaScript Error in newly build Android iOS react native application.
